spring:
  application:
    name: ssarvis

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

    mongodb:
      uri: ${MONGO_URI}

  sse:
    timeout: ${SSE_TIMEOUT} # nginx proxy timeout이랑 시간 맞추면 될듯?

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        show_sql: false
        format_sql: false
        highlight_sql: false
    open-in-view: false

  app:
    slow-query:
      threshold-ms: 1000
      csv-output-dir: ./logs/slow-queries
    slack:
      webhook-url: ${SLACK_WEBHOOK_URL}
      enabled: true
    mattermost:
      webhook-url: ${MATTERMOST_WEBHOOK_URL}
      enabled: true
    s3:
      bucket: ${S3_BUCKET_NAME}
      cloudfront-domain: ${CLOUDFRONT_DOMAIN}
    ai-server:
      url: ${AI_SERVER_URL}

  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}

jwt:
  secret-key: ${JWT_SECRET}
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_TIME}
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_TIME}

logging:
  level:
    root: INFO
    com.ssafy.ssarvis: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operations-sorter: alpha
    tags-sorter: alpha

app:
  fast-api:
    ws-url: ${FAST_API_SERVER_WS_URL}